### Create Gun
POST localhost:8081/api/v1/guns
Content-Type: application/json

{
  "name": "AK-47",
  "manufacturer": "Izhmash",
  "price": 599.99,
  "damage": 47
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Expected response status to be 201");
    });
%}

### Get Gun
GET localhost:8081/api/v1/guns/1

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Expected response status to be 200");
    });
%}

### Update Gun
PUT localhost:8081/api/v1/guns/1
Content-Type: application/json

{
  "name": "AK-47",
  "manufacturer": "Izhmash",
  "price": 699.99,
  "damage": 47
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Expected response status to be 200");
    });
%}

### Delete Gun
DELETE localhost:8081/api/v1/guns/1
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Expected response status to be 200");
    });
%}
